project_name: ordna

builds:
  - id: ordna
    main: ./cmd/ordna
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: archive
    builds: [ordna]
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE* 
      - README* 

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: git

nfpms:
  - id: linux-packages
    package_name: ordna
    maintainer: Ordna Authors
    description: Disciplined file sorter
    license: MIT
    formats: [deb, rpm]
    section: utils
    priority: optional
    dependencies: []
    contents: []
